CREATE SEQUENCE IF NOT EXISTS bookings_booking_no_seq START WITH 1001;

CREATE TABLE IF NOT EXISTS bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_no integer NOT NULL UNIQUE DEFAULT nextval('bookings_booking_no_seq'),
  lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
  customer text NOT NULL,
  email text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT 'Manual'
    CHECK (source IN ('Website', 'Google Ads', 'Meta Ads', 'Manual')),
  website text NOT NULL DEFAULT '',
  tour_package text NOT NULL DEFAULT '',
  pickup text NOT NULL DEFAULT '',
  dropoff text NOT NULL DEFAULT '',
  travel_date date,
  return_date date,
  cab_type text NOT NULL DEFAULT '',
  adults integer NOT NULL DEFAULT 0 CHECK (adults >= 0),
  kids integer NOT NULL DEFAULT 0 CHECK (kids >= 0),
  days integer NOT NULL DEFAULT 0 CHECK (days >= 0),
  tour_plan text NOT NULL DEFAULT '',
  agent text NOT NULL DEFAULT '',
  driver text NOT NULL DEFAULT '',
  vehicle text NOT NULL DEFAULT '',
  total numeric NOT NULL DEFAULT 0,
  advance numeric NOT NULL DEFAULT 0,
  balance numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Advance Pending'
    CHECK (status IN (
      'Advance Pending',
      'Advance Received',
      'Balance Pending',
      'Fully Paid',
      'Cancelled',
      'Refunded'
    )),
  hotel jsonb,
  comments jsonb NOT NULL DEFAULT '[]'::jsonb,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bookings_lead_id_idx ON bookings (lead_id);
CREATE INDEX IF NOT EXISTS bookings_status_idx ON bookings (status);
CREATE INDEX IF NOT EXISTS bookings_travel_date_idx ON bookings (travel_date);
CREATE INDEX IF NOT EXISTS bookings_updated_at_idx ON bookings (updated_at DESC);
CREATE INDEX IF NOT EXISTS bookings_website_idx ON bookings (website);

INSERT INTO bookings (
  booking_no, customer, email, city, phone, source, website, tour_package,
  pickup, dropoff, travel_date, return_date, cab_type, adults, kids, days,
  tour_plan, agent, driver, vehicle, total, advance, balance, status, hotel, comments, history
)
SELECT * FROM (
  VALUES
    (
      1182,
      'Ananya Rao'::text,
      'ananya.rao@gmail.com'::text,
      'Chandigarh'::text,
      '+91 98765 22109'::text,
      'Google Ads'::text,
      'mahasutravels.com'::text,
      '5N/6D Shimla Manali Taxi Tour'::text,
      'Chandigarh'::text,
      'Chandigarh'::text,
      '2026-08-18'::date,
      '2026-08-23'::date,
      'Innova CRYSTA (7+1)'::text,
      5,
      2,
      6,
      'Honeymoon + parents travelling together.'::text,
      'Priya'::text,
      'Suresh Thakur'::text,
      'HP-01-4521'::text,
      11000::numeric,
      5000::numeric,
      6000::numeric,
      'Advance Received'::text,
      '{"hotelTemplateId":"HT-1001","hotelName":"Hotel Willow Banks","address":"The Mall, Shimla, HP","checkIn":"2026-08-18","checkOut":"2026-08-20","roomType":"Deluxe Mountain View","roomCount":2,"amount":7200,"referenceNumber":"WB-RES-4471","contactNumber":"+91 94185 22011","notes":"Confirmed on phone"}'::jsonb,
      '[{"id":"BCM-1","text":"Hotel confirmation shared with customer on WhatsApp.","author":"Priya","createdAt":"Yesterday, 2:10 PM"}]'::jsonb,
      '[{"id":"BEV-101","action":"created","label":"Booking created","detail":"Converted from confirmed lead","actor":"Priya","createdAt":"3 days ago"}]'::jsonb
    ),
    (
      1181,
      'Manish Verma',
      'manish.verma@gmail.com',
      'Delhi',
      '+91 91125 66098',
      'Website',
      'mahasutravels.com',
      'Custom / Plan your trip',
      'Delhi',
      'Delhi',
      '2026-08-05',
      '2026-08-08',
      'Ertiga (6+1)',
      4,
      1,
      4,
      'Family sightseeing in Shimla.',
      'Aman',
      'Vinod Kumar',
      'HR-26-9981',
      15200,
      15200,
      0,
      'Fully Paid',
      NULL::jsonb,
      '[]'::jsonb,
      '[{"id":"BEV-201","action":"created","label":"Booking created","actor":"Aman","createdAt":"1 week ago"}]'::jsonb
    ),
    (
      1180,
      'Pooja Rawat',
      'pooja.rawat@gmail.com',
      'Shimla',
      '+91 99015 43201',
      'Manual',
      'himachaltaxiservice.in',
      'Cab rental only',
      'Shimla',
      'Kasauli',
      '2026-08-03',
      '2026-08-03',
      'Maruti Dezire (4+1)',
      2,
      0,
      1,
      'Day trip to Kasauli.',
      'Sana',
      'Rakesh Negi',
      'HP-08-2210',
      4800,
      0,
      4800,
      'Balance Pending',
      NULL::jsonb,
      '[{"id":"BCM-2","text":"Customer will pay on pickup.","author":"Sana","createdAt":"Yesterday"}]'::jsonb,
      '[{"id":"BEV-301","action":"created","label":"Booking created","actor":"Sana","createdAt":"5 days ago"}]'::jsonb
    ),
    (
      1190,
      'Meera Joshi',
      'meera.joshi@gmail.com',
      'Delhi',
      '+91 98111 22001',
      'Google Ads',
      'mahasutravels.com',
      '5N/6D Shimla Manali Taxi Tour',
      'Delhi',
      'Delhi',
      '2026-07-30',
      '2026-08-04',
      'Innova CRYSTA (7+1)',
      4,
      1,
      6,
      'Family Shimla–Manali circuit.',
      'Priya',
      'Suresh Thakur',
      'HP-01-4521',
      28000,
      10000,
      18000,
      'Advance Received',
      NULL::jsonb,
      '[]'::jsonb,
      '[{"id":"BEV-901","action":"created","label":"Booking created","actor":"Priya","createdAt":"2 weeks ago"}]'::jsonb
    ),
    (
      1177,
      'Ishita Bose',
      'ishita.bose@gmail.com',
      'Delhi',
      '+91 88991 20567',
      'Website',
      'mahasutravels.com',
      'Cab rental only',
      'Delhi',
      'Delhi',
      '2026-07-27',
      '2026-07-28',
      'Maruti Dezire (4+1)',
      3,
      1,
      2,
      'Weekend Mussoorie cab.',
      'Sana',
      'Rakesh Negi',
      'HP-08-2210',
      8200,
      8200,
      0,
      'Fully Paid',
      NULL::jsonb,
      '[]'::jsonb,
      '[{"id":"BEV-601","action":"created","label":"Booking created","actor":"Sana","createdAt":"2 weeks ago"}]'::jsonb
    )
) AS seed(
  booking_no, customer, email, city, phone, source, website, tour_package,
  pickup, dropoff, travel_date, return_date, cab_type, adults, kids, days,
  tour_plan, agent, driver, vehicle, total, advance, balance, status, hotel, comments, history
)
WHERE NOT EXISTS (SELECT 1 FROM bookings LIMIT 1);

SELECT setval(
  'bookings_booking_no_seq',
  GREATEST((SELECT COALESCE(MAX(booking_no), 1000) FROM bookings), 1000)
);
